name: github pages

on:
  push:
    branches: [ published ]

jobs:

  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true

      - name: Clear old public
        run: |
          rm -rf node_modules/gh-pages/.cache
          rm ./public -rf
      
      - name: Enter blog content source directory
        run: 
          cd ./blog_src

      - name: Build
        run: 
          hugo --minify --baseURL https://blog.bizliker.com

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../public
          force_orphan: false
